"""Fix backref name conflicts

Revision ID: 550acfc36633
Revises: 
Create Date: 2025-03-06 14:03:19.794229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550acfc36633'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('display',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(length=1000),
               existing_nullable=False)
        batch_op.alter_column('excerpt',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('excerpt',
               existing_type=sa.Text(length=500),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('display',
               existing_type=sa.Text(length=1000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
