"""Fix errors 

Revision ID: a014ea9f175c
Revises: 550acfc36633
Create Date: 2025-03-06 14:04:13.957898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a014ea9f175c'
down_revision = '550acfc36633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('display',
               existing_type=sa.TEXT(length=1000),
               type_=sa.Text(length=100000),
               existing_nullable=False)
        batch_op.alter_column('excerpt',
               existing_type=sa.TEXT(length=500),
               type_=sa.Text(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('excerpt',
               existing_type=sa.Text(length=5000),
               type_=sa.TEXT(length=500),
               existing_nullable=False)
        batch_op.alter_column('display',
               existing_type=sa.Text(length=100000),
               type_=sa.TEXT(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
