"""Fix errors 

Revision ID: a2bebed92934
Revises: 4d3cfcb02679
Create Date: 2025-03-06 14:22:54.496156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bebed92934'
down_revision = '4d3cfcb02679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_column('readmore_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readmore_link', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
